#ifndef LIBLIOUS_LINUX_PC_GLOBAL_H
#define LIBLIOUS_LINUX_PC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBLIOUS_LINUX_PC_LIBRARY)
#  define LIBLIOUS_LINUX_PC_EXPORT Q_DECL_EXPORT
#else
#  define LIBLIOUS_LINUX_PC_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBLIOUS_LINUX_PC_GLOBAL_H
